export default [{
  id: '0016',
  title: 'THREE.js-世界坐标和屏幕坐标之间的转换',
  label: 'THREE · WebGL',
  desc: '屏幕坐标转化为世界坐标、世界坐标转化为屏幕坐标...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/three.jpeg',
}, {
  id: '0018',
  title: 'THREE.js-性能优化',
  label: 'THREE · WebGL · 性能',
  desc: '你不知道的一些three优化...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/three.jpeg',
}, {
  id: '0019',
  title: 'THREE.js-着色器矩阵变换',
  label: 'THREE · WebGL',
  desc: '着色器中的模型矩阵、视图矩阵和投影矩阵的定义以及使用...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/three.jpeg',
}, {
  id: '0017',
  title: 'THREE.js-自定义着色器',
  label: 'THREE · WebGL',
  desc: '在Three中自定义着色器...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/three.jpeg',
}, {
  id: '0020',
  title: 'VUE-cli3+Typescript封装自己的组件UI',
  label: 'VUE . Typescript',
  desc: '通过VUE-cli3+Typescript构建封装自己的组件UI库...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/typescript.png',
}, {
  id: '0021',
  title: '在Vue中使用Typescript采坑之旅',
  label: 'VUE . Typescript',
  desc: '在使用Typescript过程中遇到的问题与解决...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/typescript.png',
}, {
  id: '0022',
  title: 'VUE性能优化',
  label: 'VUE · 性能',
  desc: 'VUE的一些性能优化...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/vue.jpeg',
}, {
  id: '0023',
  title: '图片优化',
  label: '其他 · 性能',
  desc: '图片优化...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/other.jpeg',
}, {
  id: '0024',
  title: '前端机器学习库-ml5',
  label: '机器学习',
  desc: 'ml5，p5.js的功能与使用...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/other.jpeg',
}, {
  id: '0025',
  title: 'CSS采坑之旅',
  label: 'CSS',
  desc: 'CSS采坑之旅...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/css.jpeg',
}, {
  id: '0026',
  title: '移动端兼容性采坑之旅',
  label: '其他',
  desc: '移动端兼容性采坑之旅..',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/other.jpeg',
}, {
  id: '0027',
  title: 'Flutter路由',
  label: 'Flutter',
  desc: 'Flutter路由的使用...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/flutter.jpeg',
}, {
  id: '0028',
  title: 'Flutter',
  label: 'Flutter',
  desc: 'Flutter...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/flutter.jpeg',
}, {
  id: '0029',
  title: 'SCSS',
  label: 'SCSS',
  desc: 'SCSS的一些使用规则...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/css.jpeg',
}, {
  id: '0001',
  title: 'VUE使用总结',
  label: 'Vue · vue-loader · render · 懒加载 · 过滤器',
  desc: 'vue的一些使用技巧、需要注意的东西以及一些可以优化的地方...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/vue.jpeg',
}, {
  id: '0002',
  title: '在Vue中使用Typescript(一)',
  label: 'Vue · Typescript',
  desc: '如何使用Vue + typescript创建项目，以及一些配置...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/typescript.png',
}, {
  id: '0003',
  title: '在Vue中使用Typescript(二)',
  label: 'Vue · Typescript',
  desc: 'Typescript在Vue的具体使用，@Prop、@Model、@Watch、@Emit、@Provide、@Inject、@Component、Mixins...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/typescript.png',
}, {
  id: '0004',
  title: 'CSS伪元素',
  label: 'CSS · 伪元素',
  desc: 'CSS伪元素详解...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/css.jpeg',
}, {
  id: '0005',
  title: 'ELement采坑之旅',
  label: 'ElementUI',
  desc: '使用Element过程中遇到的坑以及觉得需要记录的东西...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/element.jpg',
}, {
  id: '0006',
  title: '跨域那点事',
  label: '跨域 · JSONP · CORS · postMessage',
  desc: '介绍跨域的原因以及解决方案...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/other.jpeg',
}, {
  id: '0007',
  title: '移动事件封装Tap',
  label: 'touch · 封装Tap',
  desc: '将移动端的点击事件封装成Tap...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/touch.jpeg',
}, {
  id: '0008',
  title: 'JS拖拽',
  label: 'Javascript',
  desc: '关于元素拖拽的解决方法...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/typescript.png',
}, {
  id: '0009',
  title: 'React-Webpack-多入口多出口',
  label: 'React · Webpack',
  desc: 'react-webpack关于多入口多出口的配置...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/react.jpg',
}, {
  id: '0010',
  title: 'VUE-cli3搭建项目-webpack配置',
  label: 'VUE-cli3 · Webpack',
  desc: 'vue-cli3将webpack的基础配置全部内嵌了，如何进行webpack配置...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/webpack.jpeg',
}, {
  id: '0011',
  title: '元素居中',
  label: 'CSS',
  desc: '水平居中、垂直居中、水平垂直居中...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/css.jpeg',
}, {
  id: '0012',
  title: '从输入 URL 到页面加载完成的过程中都发生了什么事情',
  label: '其他',
  desc: '从输入 URL 到页面加载完成的过程中都发生了什么...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/other.jpeg',

}, {
  id: '0013',
  title: '浏览器渲染过程',
  label: '其他',
  desc: '浏览器工作原理...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/other.jpeg',
}, {
  id: '0014',
  title: '常见的CSS图形绘制合集',
  label: 'CSS',
  desc: '正方形、圆、三角形、箭头...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/css.jpeg',
}, {
  id: '0015',
  title: 'HTTP2',
  label: 'HTTP · 其他',
  desc: 'HTTP2协议的特点以及优势...',
  path: 'https://sanchunpeng.github.io/pscblog/src/assets/other.jpeg',
}];
